version: 2
jobs:
  build:
    environment:
      - JAVA_OPTS: "-XX:ReservedCodeCacheSize=256M -Xms1g -Xmx3g -Xss2m"
      - AWS_REGION: "ap-northeast-1"
    machine: true
    steps:
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y libaio1 libevent-dev
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:webupd8team/java
            sudo apt-get update -qq
            echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
            sudo apt-get install -y oracle-java8-installer
            sudo apt-get install -y sbt maven git
      - checkout
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run:
          command: |
            git submodule update --init
            cd aws-sdk-src/aws-sdk-java-v2
            mvn install
            sbt ++2.11.12 test:compile && sbt ++2.12.8 test:compile
      - save_cache:
          paths: [ "~/.sbt/boot", "~/.ivy2", "~/.wixMySQL", "aws-sdk-src" ]
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run:
          command: |
            sbt ++2.11.12 test && sbt ++2.12.8 test